import type { ItemData } from "../../types";

export function createDefaultItem(nextId: number): ItemData {
  return {
    id: nextId,
    name: "New Item",
    description: "",
    type: "misc",
    subtype: "",
    rarity: "common",
    weight: 0,
    value: 0,
    stackable: false,
    max_stack: 1,
    icon_path: "",
    equippable: false,
    slot: "",
    level_requirement: 0,
    durability: -1,
    max_durability: -1,
    repairable: false,
    usable: false,
    weapon_data: null,
    armor_data: null,
    consumable_data: null,
    special_effects: [],
    attributes_bonus: {},
  };
}

export const KNOWN_ITEM_KEYS = new Set([
  "id",
  "name",
  "description",
  "type",
  "subtype",
  "rarity",
  "weight",
  "value",
  "stackable",
  "max_stack",
  "icon_path",
  "equippable",
  "slot",
  "level_requirement",
  "durability",
  "max_durability",
  "repairable",
  "usable",
  "weapon_data",
  "armor_data",
  "consumable_data",
  "special_effects",
  "attributes_bonus",
]);
